### ISSUE TITLE
RCM loader import file problem

### ISSUE THREAD

**Issue by f840810** [carcaschoi/rcmloader-package#1]
Hi, 
Here is my problem(it might be a bit easy for you...)

I have purchased an RCM loader one (from xkit.xyz) and I also updated the firmware of it from v1.0 to v1.2

And then, should I still need to copy the uncompressed files into my RCM loader? or I just uses the RCM loader(v1.2) without your uploaded files and inject the payload?

thanks for your patience and wait for your comments

**Comment by carcaschoi** [comment]
You should update it if you want to use ShallowSea aio package
